<?php
/**
 * @file
 * A block module that displays the tophat portion 
 */
/**
 * Implements tophat_help().
 */
function tophat_help($path, $arg) {

  if ($path == 'admin/help#shownodes') {
    $output = '<h3>' . t('About') . '</h3>';
    $output .= '<p>' . t('The tophat module displays the top bar on Drupal Pages.') . '</p>';
    return $output;
  }
}

function tophat_printout($op) {

 
    $output = '<h3>tophat</h3>';
    $output .= '<p>tophat info</p>';
    return $output;
  }
